#!/usr/bin/env python
# -*- mode: python; coding: utf-8; -*-
##---------------------------------------------------------------------------##
##
## Copyright (C) 1998-2003 Markus Franz Xaver Johannes Oberhumer
## Copyright (C) 2003 Mt. Hood Playing Card Co.
## Copyright (C) 2005-2009 Skomoroh
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <http://www.gnu.org/licenses/>.
##
##---------------------------------------------------------------------------##

from mahjongg import r

# test
#r(5991, "AAA 1", ncards=4, layout="0daa")
#r(5992, "AAA 2", ncards=8, layout="0daadca")
#r(5993, "AAA 3", ncards=20, layout="0daaCabdacKbbdcaCcbdcc")
#r(5994, "AAA 4", ncards=20, layout="0daaDabdacdcaDcbdcc")

# ************************************************************************
# * game definitions
# ************************************************************************

r(5401, "Taipei", layout="0aagabbabdabjablhccacfachhckadbaddhdehdghdiadjadlhecaefoegaehhekafcifehfgvfgifiafkagahgcageaggoggagihgkagmhhaahcohehhfvhfhhhvhhohiahkhhmaiahidaieaigoigCigaiihijaimhjbajcojehjfvjfJjghjhvjhojiajkhjlakahkdakeakgokgCkgQkgakihkjakmhlbalcolehlfvlfJlghlhvlholialkhllamahmdameamgomgCmgamihmjammhnaanconehnfvnfhnhvnhoniankhnmaoahocaoeaogoogaoihokaomapcipehpgvpgipiapkhqcaqfoqgaqhhqkarbardhrehrghriarjarlhscasfashhskatbatdatjatlaug")
r(5402, "Hare", layout="0aacaamacabccaceackbcmacobeacecbeebekcembeoofavfcofeofkvfmofobgacgcbgebgkcgmbgoaiabicbiebikbimaioakcakebkhakkakmamebmgbmiamkbogoohboicqfcqhcqjasejsfasgjshasijsjaskCtgCtibuddufduhdujbulovdCvgCviovlbwddwfdwhdwjbwlcyfcyhcyjbAhbCh")
r(5403, "Horse", layout="0bafbahbajbcdbchbclaedbefbehbejaelagfaghagjaifhigaihhiiaijakfhkgakhhkiakjbmecmgcmibmkcodcofcohcojcolcqdcqfvqgcqhvqicqjcqlbsbcsfvsgcshvsicsjbsnotbotnbubcudcufvugcuhvuicujculbunbwbcwdcwfcwhcwjcwlbwnbycayfbyhayjbymaAbaAnaCaaCo")
r(5404, "Rat", layout="0aaabacoadbaeaagbcacccccebcgvddodgbeacecceebegagabgcbggagmbicbieaigaimckeckgckiakmblcblkcmevmfcmgvmhcmibmmamobncCngbnkhnocoevofcogvohcoibomaoobpcbpkcqecqgcqiaqmbscbseasgasmauabucbugaumbwacwccwebwgvxdoxgbyacyccyebygaAabAcoAdbAeaAg")
r(5405, "Tiger", layout="0baabacbambaobcabccbcmbcobebaeghehaeibenbgbbggbgibgnaibbidcifcihdijbilainakdhkeakfokfhkgakhpkhhkiakjokjhkkaklbmepmfbmgomhbmiomjbmkboeoofbogoohboipojbokbqeoqfbqgpqhbqioqjbqkbsddsfcshcsjbslbubbudbuhbulbunbwbbwibwnbybbygbynbAbbAibAnbCbbCgbCn")
r(5406, "Ram", layout="0aacaaeaagaaihbehbghbibccaceoceacgaciociackadaodchdehdihdkheabecaeepeeaeioeiaekafaofchfehfihfkhgabgcageogeaggagiogiagkahahhehhghhibicaieaigaiibkcblgbmcbmeamionehniankanmcocboevoebogaoiooihokhombooopehpiapkapmbqcbqeaqibrgbscbucaueaugauiavahvehvghvihwabwcaweoweawgawiowiawkaxaoxchxehxihxkhyabycayepyeayioyiaykazaozchzehzihzkbAcaAeoAeaAgaAioAiaAkhBehBghBiaCcaCeaCgaCi")
r(5407, "Wedges", layout="0aagbaicakdamacaacibckccmbeaaecaekbemcgabgcageagmdiacicbieaigekadkcckebkgakiakohlofmaemcdmecmgbmiamkammamoomohnoeoaeocdoecogaoiaoodqadqccqeaqgcsacscaseasmbuaaucaukbumawaawibwkcwmaygbyicykdym")
r(5408, "Monkey", layout="0aaahabaacoachadaaeaakbcaaceackhclacmocmhcnacoodabeabeoofoagahgbagcaghbgobicbigbiiaimhinaioojgbkcdkebkgvkgdkibkkbkmolgdmebmgvmgdmiongdoebogvogdoiaokholaomaooopghpobqcdqebqgvqgdqiaqooqoorghroasahsbascbsgasmasoauaaughuhauiawihwjawkowkhwlawmbymaAchAdaAeoAehAfvAfaAgoAgCAghAhvAhaAioAiCAihAjvAjaAkoAkhAlaAmaCahCbaCc")
r(5409, "Rooster", layout="0aaaaagabchcccceccgadcvdfadiceecegaeohfoageagoogohhoaiehifaigaimaiohjmbkeokfbkgokhbkiakkakmamccmevmfcmgvmhcmiamkanahncCnghoaaocooccoevofcogvohcoiapaopahpchqaaqcoqcbqeoqfbqgvqgoqhbqiaqkaqmaraorahrchrmhsaascbsgoshbsiaskasmasoataotahtohuaaufhugauhauoavabweowfbwgowhbwivxgayabycoydbyeoyfbygoyhbyihzaaAaaAeaAjhAkaAlhBaaCaaCehCfaCgaCl")
r(5410, "Dog", layout="0aaeaaghbehbgaccaceoceacgocgaciackhdchdehdghdihdkaecoecaeeaegaeiaekhfcagcaichidaieoiehifaigvjebkackcckeckgbkibkkvlcoliolkbmacmccmgbmibmkamoonavnconkboacoccoecogbokaomaooopavpcopkbqacqccqgbqibqkvrcoriorkbsacsccsecsgbsibskvteauchudaueouehufaugawchxcaycoycayeaygayiaykhzchzehzghzihzkaAcaAeoAeaAgoAgaAiaAkhBehBgaCeaCg")
r(5411, "Snake", layout="0bagbaiobhbcgbcibdebecbegbfebgcbhabicbiicikcimbjavjlbkcbkebkgbkickkckmakooleolgolivllhlobmcbmebmgbmicmkcmmamoomovnlhnocokcomaooooovplhpobqcbqebqgbqicqkcqmaqooreorgorivrlbscbsebsgbsicskcsmbtabucbvabwcbwebwgbwibwkbycbyebygbyibykbAjaCj")
r(5412, "Boar", layout="0aacaaehafaagoaghahaaiaakhbchbkaccoccaciackockacmhdchdkhdmaecaeeaekoekaemoemhfkhfmagiagkogkagmhhkaiiaikakcbkgbkiakmolgolibmcbmebmgbmibmkbmmonconepngpnionkonmanoaoabocvocboevoebogboibokvokbomvomhooopcopeppgppiopkopmapobqcbqebqgbqibqkbqmorgoriascbsgbsiasmauiaukhvkawiawkowkawmhxkhxmaycayeaykoykaymoymhzchzkhzmaAcoAcaAiaAkoAkaAmhBchBkaCcaCehCfaCgoCghChaCiaCk")
r(5413, "Ox", layout="0aahabeabkbcgochbciaeaaecbegbeiaemaeohfbhfnagaagcagebggbgiagkagmagoaicbiebigbiibikaimakcbkeckgckibkkakmbmecmgcmibmkaodioeaofjogaohjoiaojiokaolcqedqgdqicqkcsedsgdsicskaucbuecugcuibukaumawcbwecwgcwibwkawmayaaycayebygbyiaykaymayohzbhznaAaaAcaAhaAmaAo")
r(5414, "Bridge 2", layout="0daadacdaedagdaidakdamdaoccccceccgccicckccmbeebegbeibekaggagiaihhjhakhokhhlhvlhamfamhomhCmhhnhvnhJnhanjaofaohoohCohhphvphaqhoqhhrhashaugauibwebwgbwibwkcyccyecygcyicykcymdAadAcdAedAgdAidAkdAmdAo")

##----------------------------------------------------------------------

#r(5501, "Big X", layout="0aacaamhbchbmacboccacdaclocmacnhdbhddhdlhdnaeaaecoedaeeaekoelaemaeohfchfehfkhfmagbagdogeagfagjogkaglagnhhdhhfhhjhhlaicaieoifaigaiioijaikaimhjehjghjihjkakdakfokgakhokiakjaklhlfhlhhljameamgomgamiomiamkhnfhnhhnjaofoofaohoohaojoojhpfhphhpjaqeaqgoqgaqioqiaqkhrfhrhhrjasdasfosgashosiasjaslhtehtghtihtkaucaueoufaugauioujaukaumhvdhvfhvjhvlawbawdoweawfawjowkawlawnhxchxehxkhxmayaaycoydayeaykoylaymayohzbhzdhzlhznaAboAcaAdaAloAmaAnhBchBmaCcaCm")
#r(5502, "Axis", layout="0bafcahbajbbdvbhbblcchCchbdcvdhbdmcehCehbfbvfhbfncghahaahohiahioajabjhajohkabkfbkjhkoalabldbllalohmacmhhmoanaancvnhanmanoiobcohionapbwphapniqbcqhiqnaraarcvrharmarohsacshhsoatabtdbtlatohuabufbujhuoavabvhavohwahwoaxaaxocyhbzbvzhbzncAhCAhbBcvBhbBmcChCChbDdvDhbDlbEfcEhbEj")
#r(5503, "Cobweb", layout="0aacaafhagaahoahhaiaajaamacbhccacdaclhcmacnadfhdgadhodhhdiadjaeaaeohfaafcafeafhafkafmhfoagaogaagoogohhaahcahhahmhhoaiaoiaaiooiohjaajdajhajlhjoakaakoalealhalkamaamoancanfhnganhhnianjanmaoahoboogooihonaooopbapcbpgvpgbpivpiapmopnaqahqboqgoqihqnaqoarcarfhrgarhhriarjarmasaasoateathatkauaauohvaavdavhavlhvoawaowaawoowohxaaxcaxhaxmhxoayaoyaayooyohzaazcazeazhazkazmhzoaAaaAoaBfhBgaBhoBhhBiaBjaCbhCcaCdaClhCmaCnaEcaEfhEgaEhoEhhEiaEjaEm")
#r(5504, "Pyramids", layout="0aaaaacaakaamhbbabeabgabihblacaaccackacmhdbadeadgadihdlaeaaecaekaemaffhfgafhahbaheahiahlhibhiehiihilajbojbajdojeajfajhojiajjajlojlhkbvkbhkevkehkghkivkihklvklalbolbClbaldoleClealfolgalholiClialjallollCllhmbvmbhmevmehmgvmghmivmihmlvmlanbonbCnbandoneCneanfonganhoniCnianjanlonlCnlhobvobhoevoehoghoivoiholvolapbopbapdopeapfaphopiapjaploplhqbhqehqihqlarbareariarlatfhtgathauaaucaukaumhvbaveavgavihvlawaawcawkawmhxbaxeaxgaxihxlayaaycaykaym")
#r(5505, "Wicker", layout="0bafbakbbcbbhbbmbcebcjbdbbdgbdlbedbeibenbfabffbfkbgcbghbgmbhebhjbibbigbilbjdbjibjnbkabkfbkkblcblhblmbmebmjbnbbngbnlbodboibonbpabpfbpkbqcbqhbqmbrebrjbsbbsgbslbtdbtibtnbuabufbukbvcbvhbvmbwebwjbxbbxgbxlbydbyibynbzfbzkbAh")

##----------------------------------------------------------------------

r(5801, "Faro", name="Double Mahjongg Faro", ncards=288, layout="0aaahabaachadaaeoaehafaagiahaaihajaakoakhalaamhanaaoobcvbhobmacbhccvccacdacgichCchaciaclhcmvcmacnodcCdcvdhodmCdmaebhecvecaedheeaefcehCehaejhekaelhemvemaenofcvfhofmbgcagfhggaghoghhgiagjbgmahaahohiahioajapjaajccjebjhcjkajmajopjohkahkcokhhkmhkoalaalcqlcalfhlgalhvlhhlialjalmqlmalohmcomhCmhhmmanbqncandhneanfbnhvnhanjhnkanlqnmannhocooeoohookhomapcppcCpdbpevpebphwphbpkvpkCplapmppmhqcoqeoqhoqkhqmarbqrcardhrearfbrhvrharjhrkarlqrmarnhscoshCshhsmataatcqtcatfhtgathvthhtiatjatmqtmatohuahucouhhumhuoavapvaavccvebvhcvkavmavopvohwahwoaxaaxobycayfhygayhoyhhyiayjbymozcvzhozmaAbhAcvAcaAdhAeaAfcAhCAhaAjhAkaAlhAmvAmaAnoBcCBcvBhoBmCBmaCbhCcvCcaCdaCgiChCChaCiaClhCmvCmaCnoDcvDhoDmaEahEbaEchEdaEeoEehEfaEgiEhaEihEjaEkoEkhElaEmhEnaEo")
#r(5802, "Big Square", name="Double Mahjongg Big Square", ncards=288, layout="0daadacdaedagdaidakdcadccdcedcgdcidckdeadecdeedegdeidekdgadgcdgedggdgidgkdiadicdiedigdiidikdkadkcdkedkgdkidkkdmadmcdmedmgdmidmkdoadocdoedogdoidokdqadqcdqedqgdqidqkdsadscdsedsgdsidskduaducduedugduidukdwadwcdwedwgdwidwk")
r(5803, "Two Squares", name="Double Mahjongg Two Squares", ncards=288, layout="0daadacdaedagdaidakdcadccdcedcgdcidckdeadecdeedegdeidekdgadgcdgedggdgidgkdiadicdiedigdiidikdkadkcdkedkgdkidkkdoadocdoedogdoidokdqadqcdqedqgdqidqkdsadscdsedsgdsidskduaducduedugduidukdwadwcdwedwgdwidwkdyadycdyedygdyidyk")
#r(5804, "Rows", name="Double Mahjongg Rows", ncards=288, layout="0daadacCaddaeCafdagCahdaidakdcadckeeadeceeeeegdeieekegaegkeiadiceieeigdiieikekaekkemadmcemeemgdmiemkeoaeokeqadqceqeeqgdqieqkesaeskeuaduceueeugduieukewaewkeyadyceyeeygdyieykdAadAkdCadCcCCddCeCCfdCgCChdCidCk")
r(5805, "Twin Picks", name="Double Mahjongg Twin Picks", ncards=288, layout="0aacaaeaagaaiaakaamhbdhbfhbhhbjhblacaaccaceoceacgocgaciociackockacmacohdbhddhdfvdfhdhvdhhdjvdjhdlhdnaeaaecoecaeeoeeaegoegCegaeioeiCeiaekoekaemoemaeohfbhfdvfdhffvffhfhvfhhfjvfjhflvflhfnagaagcogcageogeCgeaggoggCggagiogiCgiagkogkCgkagmogmagohhbhhdvhdhhfvhfhhhvhhhhjvhjhhlvhlhhnaiaaicoicaieoieaigoigCigaiioiiCiiaikoikaimoimaiohjbhjdhjfvjfhjhvjhhjjvjjhjlhjnakaakcakeokeakgokgakiokiakkokkakmakohldhlfhlhhljhllamcameamgamiamkammapaapcapeapgapiapkapmapoascaseasgasiaskasmhtdhtfhthhtjhtlauaaucaueoueaugougauiouiaukoukaumauohvbhvdhvfvvfhvhvvhhvjvvjhvlhvnawaawcowcaweoweawgowgCwgawiowiCwiawkowkawmowmawohxbhxdvxdhxfvxfhxhvxhhxjvxjhxlvxlhxnayaaycoycayeoyeCyeaygoygCygayioyiCyiaykoykCykaymoymayohzbhzdvzdhzfvzfhzhvzhhzjvzjhzlvzlhznaAaaAcoAcaAeoAeaAgoAgCAgaAioAiCAiaAkoAkaAmoAmaAohBbhBdhBfvBfhBhvBhhBjvBjhBlhBnaCaaCcaCeoCeaCgoCgaCioCiaCkoCkaCmaCohDdhDfhDhhDjhDlaEcaEeaEgaEiaEkaEm")
r(5806, "Roost", name="Double Mahjongg Roost", ncards=288, layout="0aaahabaacoachadvadaaeoaehafvafaagoaghahvahaaioaihajaakaamaaoCbfhblhbnacbhccacdocdhcevceacfocfhcgvcgachochhciacjaclocmacnhdkhdmaeiaekoelaemaeoafaafcafehfjhflvflhfnhgchgeaghagjogkaglCglogmagnahbohcahdoheahfhhihhkvhlhhmhibhidviehifaiioijaikoilaimajaajcojdajeCjeojfajghjjvjkhjlajohkcvkdhkevkfhkgakjokkaklalbolcaldolealfClfolgalhhlkblnhmbhmdvmehmfvmghmhamkomnanaancondaneonfangCngonhanianmhnnanohochoevofhogvohhoiapbapdopeapfopgaphCphopiapjhpkaploplhpmapnhqchqevqfhqgvqhhqiaraarcordareorfargCrgorhariarmhrnarohsbhsdvsehsfvsghshaskosnatbotcatdoteatfCtfotgathhtkbtnhucvudhuevufhugaujoukaulavaavcovdaveCveovfavghvjvvkhvlavohwbhwdvwehwfawiowjawkowlawmaxboxcaxdoxeaxfhxihxkvxlhxmhychyeayhayjoykaylCyloymaynazaazcazehzjhzlvzlhznaAiaAkoAlaAmaAohBkhBmaCbhCcaCdoCdhCevCeaCfoCfhCgvCgaChoChhCiaCjaCloCmaCnCDfhDlhDnaEahEbaEcoEchEdvEdaEeoEehEfvEfaEgoEghEhvEhaEioEihEjaEkaEmaEo")
r(5807, "Castle", name="Double Mahjongg Big Castle", ncards=288, layout="0eaadacdaeeageaidakdameaodcadcocddvdecdfvdgcdhCdhvdicdjvdkcdldeadeoafdaflcgacgoahdahlciacioajdajlckahkdhklckoaldelfblheljallcmahmdhmlcmoandbnfbnjanleoahodoofoojholeooapdbpfvpfbpjvpjapleqahqdoqfoqjhqleqoardbrfbrjarlcsahsdhslcsoatdetfbthetjatlcuahudhulcuoavdavlcwacwoaxdaxlcyacyoazdazldAadAocBdvBecBfvBgcBhCBhvBicBjvBkcBldCadCoeEadEcdEeeEgeEidEkdEmeEo")
r(5808, "Eight Squares", name="Double Mahjongg Eight Squares", ncards=288, layout="0daadacdaedahdajdaldcadccdcedchdcjdcldeadecdeedehdejdeldhadhcdhedhhdhjdhldjadjcdjedjhdjjdjldladlcdledlhdljdlldoadocdoedohdojdoldqadqcdqedqhdqjdqldsadscdsedshdsjdsldvadvcdvedvhdvjdvldxadxcdxedxhdxjdxldzadzcdzedzhdzjdzl")
r(5809, "Big Flying Dragon", name="Double Mahjongg Big Flying Dragon", ncards=288, layout="0aajacaaciackacsaeaaegaeihejaekaemaesagaageaggbgibgkagmagoagsaiaaicaiebigbiibikbimaioaiqaisakabkcbkebkgbkibkkbkmbkobkqaksbmabmccmecmgcmicmkcmmcmobmqbmsboaboccoedogdoidokdomcooboqbosbqabqccqedqgeqieqkdqmcqobqqbqsJrjbsabsccsedsgesieskdsmcsobsqbssbuabuccuedugduidukdumcuobuqbusbwabwccwecwgcwicwkcwmcwobwqbwsayabycbyebygbyibykbymbyobyqaysaAaaAcaAebAgbAibAkbAmaAoaAqaAsaCaaCeaCgbCibCkaCmaCoaCsaEaaEgaEihEjaEkaEmaEsaGaaGiaGkaGsaIaaIjaIsaKj")
r(5810, "Sphere", name="Double Mahjongg Sphere", ncards=288, layout="0aajaalaanabhhbkhbmabpacfhciacjockaclocmacnhcoacraddhdgadhodivdkhdlvdmodoadphdqadtaefoegveihejaekoekaemoemhenveooeqaerafchfdhffhfhafiafohfphfrhftafuageogeaggpggpgihgjpgkbglpgmhgnpgoagqpgqagsogsahbhhchhfhhhahjahnhhphhrhhuahvaidoidvieaifoigaihoiihijoikbiloimhinoioaipoiqairvisaitoitajahjbhjdhjfhjhvjlhjphjrhjthjvajwakcokcvkdakeokeakgokgakiokiakkokkakmokmakookoakqokqaksoksvktakuokualahlbhldhlfvlfhlhvlhhljvljhllvllhlnvlnhlpvlphlrvlrhlthlvalwamcomcvmdameomeamgomgamiomiamkomkammommamoomoamqomqamsomsvmtamuomuanahnbhndhnfhnhvnlhnphnrhnthnvanwaodoodvoeaofoogaohooihojookboloomhonoooaopooqaorvosaotootapbhpchpfhphapjapnhpphprhpuapvaqeoqeaqgpqgpqihqjpqkbqlpqmhqnpqoaqqpqqaqsoqsarchrdhrfhrhariarohrphrrhrtaruasfosgvsihsjaskoskasmosmhsnvsoosqasratdhtgathotivtkhtlvtmotoatphtqattaufhuiaujoukauloumaunhuoauravhhvkhvmavpawjawlawn")

##----------------------------------------------------------------------

r(5901, "Happy New Year", name="Half Mahjongg Happy New Year", ncards=72, layout="0aafaajaanaceaciacmbedbehaelofdofhhflbgdbghaglohdohhaibbidaighihaiiailhimainojmakaakeckhakjbkmbkoolmambbmdamghmhamiamlhmmamnondonhbodbohaolopdophhplbqdbqhaqlaseasiasmaufaujaun")
#r(5902, "K 2", name="Half Mahjongg K 2", ncards=72, layout="0aagabcabehbfobghbhabiabkacgvcgadbidgadlaegvegbfaifgbfmaggbhaihgbhmaigbjahjgbjmakgokgblahlgblmamgbnaingbnmaogbpaipgbpmaqgvqgarbirgarlasgvsgatcatehtfotghthatiatkaug")
#r(5903, "Abstract", name="Half Mahjongg Abstract", ncards=72, layout="0aaaaagabcabebddadgadioedhehafchfdafeafhagahhaahdahgaiahjaojbbjcajfakaalcamfamhanbhncandhngaogboiapdhqdaqiarcordarehrihsdasgasiatdauaaufhvbavcaviawaawehxeaxiaycayebyghzdaAdaAhaBbaBfhCfaCiaDcaDeaDghDhaEaaEi")
r(5904, "Smile", name="Half Mahjongg Smile", ncards=72, layout="0bagoahbaibbebbkbccbcmbebbenaffbfjbgahgfbgoahfbhkbiabiobjlbkabkobllbmabmoanfbnkboahofbooapfbpjbqbbqnbscbsmbtebtkbugouhbui")
r(5905, "Wall", name="Half Mahjongg Wall", ncards=72, layout="0eaabacbaebagbaibakbameaoacaacoaeaaeoagaagoaiaaioakaakoamaamoaoaaooaqaaqoasaasoauaauoawaawoayaayoaAaaAoaCaaCoeEabEcbEebEgbEibEkbEmeEo")

##----------------------------------------------------------------------

#r(5601, "Skomoroh 1", ncards=28, layout="0aacaaeaaghbdhbfacaacdoceacfacihddhdfaebaeeoeeaehhfdhffagaagdogeagfagihhdhhfaicaieaig")
#r(5602, "Skomoroh 2", ncards=116, layout="0aaeaaghahaaiaakabaaboacfbchacjadaadoaeghehaeiafaafocghahaahcahfvhhahjahmahohidcihhilajaajdajfwjhajjajlajohkdhkgakhokhhkihklalaalcalewlhalkalmalohmfamgimhamihmjanaancanewnhankanmanohodhogaohoohhoiholapaapdapfwphapjaplapohqdcqhhqlaraarcarfvrharjarmarocshataatoaughuhauiavaavoawfbwhawjaxaaxoayeayghyhayiayk")
#r(5603, "Skomoroh 3", ncards=132, layout="0aachadaaeoaeXaehafyafaagoagXaghahaaiabaabkhcahckadaadeadgadkheahefhekafaafeafgafkhgahgfhgkahaaheahgahkhiahifhikajaajeajgajkhkahkfhkkalaalealgalkhmahmfhmkanaaneonfangankhofXofapbapdapfspfaphapjhqfXqfaraareorfargarkhsahsfhskataateatgatkhuahufhukavaaveavgavkhwahwfhwkaxaaxeaxgaxkhyahyfhykazaazeazgazkhAahAfhAkaBaaBeaBgaBkhCahCkaDaaDkaEchEdaEeoEeXEehEfyEfaEgoEgXEghEhaEi")
#r(5604, "Skomoroh 4", ncards=52, layout="0aajaalaanabhabpacfacnacraddadladtaejafcafuagiahbbhoahvaiiajaajwakjalaalwamkammanaanwaonapaapwaqoarbbriarvasoatcatuaunavdavlavtawfawjawraxhaxpayjaylayn")
#r(5605, "Skomoroh 5", ncards=208, layout="0aahaajaalaanaaphbihbkoblhbmhboaccaceacgaciackacmacoacqacsacuaecaeuagdagjaglagnagthhkhhmaieaijailoilainaishjkhjmakfakjakloklaknakrhlkhlmameamgamjamlomlamnamqamsanchndhnkhnmhntanuaoeaohaojaoloolaonaopaosapchpdhpkhpmhptapuaqeaqhaqjaqlaqnaqpaqsaraarchrdhrtaruarwaseasgasiaskasmasoasqassatahtbatchtdhtfithitjitlitnitphtrhttatuhtvatwaueaugauiaukaumauoauqausavaavchvdhvtavuavwaweawhawjawlawnawpawsaxchxdhxkhxmhxtaxuayeayhayjayloylaynaypaysazchzdhzkhzmhztazuaAeaAgaAjaAloAlaAnaAqaAshBkhBmaCfaCjaCloClaCnaCrhDkhDmaEeaEjaEloElaEnaEshFkhFmaGdaGjaGlaGnaGtaIcaIuaKcaKeaKgaKiaKkaKmaKoaKqaKsaKuhLihLkoLlhLmhLoaMhaMjaMlaMnaMp")
#r(5606, "Skomoroh 6", layout="0aadaafaahaajaalaanaapadaaddadfadhadjadladnadpadsheehegheihekhemheoafaafdaffoffafhofhafjofjafloflafnofnafpafshgehggvgghgivgihgkvgkhgmvgmhgoahaChhChjChlahsaidaifoifaihoihJiiaijoijJikailoilainoinaipajahjehjgvjgCjhhjivjihjkvjkCjlhjmvjmhjoajsakdakfokfakhokhJkiakjokjJkkakloklaknoknakpalaClhCljCllalshmehmgvmghmivmihmkvmkhmmvmmhmoanaandanfonfanhonhanjonjanlonlannonnanpanshoehoghoihokhomhooapaapdapfaphapjaplapnappapsasdasfashasjaslasnasp")
#r(5607, "Skomoroh 7", ncards=56, layout="0aabaadaafaahaajaapaaraatablabwadaadmadwafaafnafwahaahnahwajfajhajmajwakdakjalbdllalvamnamtanaankanpanrapaapjapwaraarjarwataatkatwavaavlawdawfawhawnawpawrawtawv")

