#!/bin/bash
set -eux
# Download android support library from maven

. mkp4a.common

liburl="https://maven.google.com/com/android/support/support-v4/24.1.1"
libname="support-v4-24.1.1.aar"

. mkp4a.preload supportlib ${liburl} ${libname}
