#!/bin/bash
set -eux

. mkp4a.common

echo '### prepare cardsets'

if [ ! -f ${cardsets_file} ]; then
  echo '### downloading cardsets'
  wget https://netix.dl.sourceforge.net/project/pysolfc/PySolFC-Cardsets/minimal/${cardsets_file}
fi

if [ ! -d ${cardsets_dir} ]; then
  echo '### extracting cardsets'
  tar -xf ${cardsets_file}
fi

echo '### processing cardsets'
(
  cd ${cardsets_dir}
  ../../scripts/cardconv
  for i in cardset-*-bmp; do
    rm -rf `basename $i -bmp`
  done
)

echo '### end cardsets'
