#!/bin/bash

# memo:
# keytool -genkey -v -keystore my-release-keystore -alias alias_name -keyalg RSA -keysize 2048 -validity 12000

if [ ! -d bin ]
then
  echo "mkdir bin"
  mkdir bin
fi

if [ -f ./bin/keystore ]
then
  echo "keystore is already defined"
else
  keytool -genkey -v -keystore ./bin/keystore -alias python -keyalg RSA -keysize 2048 -validity 12000
fi
