#!/bin/bash

appdir=""
if [ "$1" ]
then
  appdir=$1
else
	exit 1
fi

# current android version mumber.
version="3.6.1"
sversion=$(echo $version  | sed -E "s:(.*)\..*:\1:")
tuple=$(echo $version | sed -E "s:(.*)\.(.*)\.(.*):(\1, \2, \3):")

# patch different version info accordingly.
tmp1=$(mktemp)
sed -E "s:VERSION_TUPLE =.*:VERSION_TUPLE = $tuple:" \
    $appdir/pysollib/settings.py > "$tmp1"
mv "$tmp1" $appdir/pysollib/settings.py

tmp2=$(mktemp)
sed -E "s:(.*\(')dev(',.*):\1fc-$sversion\2:" \
    $appdir/pysollib/gamedb.py > "$tmp2"
mv "$tmp2" $appdir/pysollib/gamedb.py

echo "VERSION = $version"
