#!/bin/bash
set -eux

cardsets_dir=PySolFC-Cardsets--Minimal-2.2.0
cardsets_file=${cardsets_dir}.tar.xz

rm -rf cardsets

echo '### prepare cardsets'

if [ ! -f ${cardsets_file} ]; then
  echo '### downloading cardsets'
  wget https://netix.dl.sourceforge.net/project/pysolfc/PySolFC-Cardsets/minimal/${cardsets_file}
fi

if [ ! -d ${cardsets_dir} ]; then
  echo '### extracting cardsets'
  tar -xf ${cardsets_file}
fi

echo '### processing cardsets'
(
  cd ${cardsets_dir}
  ../../scripts/cardconv gif png
  for i in cardset-*-png; do
    rm -rf `basename $i -png`
  done
)

ln -s ${cardsets_dir} cardsets

echo '### end cardsets'
