#!/usr/bin/env python
import os.path
for module_name in ['pysollib.app', 'pysollib.acard', 'pysollib.actions', 'pysollib.customgame', 'pysollib.help', 'pysollib.hint', 'pysollib.images', 'pysollib.init', 'pysollib.main', 'pysollib.layout', 'pysollib.mfxutil', 'pysollib.move', 'pysollib.options', 'pysollib.pysolrandom', 'pysollib.resource', 'pysollib.settings', 'pysollib.stack', 'pysollib.stats', 'pysollib.mygettext', 'pysollib.wizardpresets', 'pysollib.util', 'pysollib.gamedb', 'pysollib.configobj.configobj', 'pysollib.configobj.validate', 'pysollib.game', 'pysollib.pysoltk', 'pysollib.pysolaudio', 'pysollib.wizardutil', 'pysollib.winsystems.aqua', 'pysollib.winsystems.common', 'pysollib.winsystems.x11', 'pysollib.winsystems.win32', 'pysollib.macosx.appSupport', 'pysollib.pysolgtk.card', 'pysollib.pysolgtk.colorsdialog', 'pysollib.pysolgtk.edittextdialog', 'pysollib.pysolgtk.findcarddialog', 'pysollib.pysolgtk.fontsdialog', 'pysollib.pysolgtk.gameinfodialog', 'pysollib.pysolgtk.menubar', 'pysollib.pysolgtk.playeroptionsdialog', 'pysollib.pysolgtk.progressbar', 'pysollib.pysolgtk.pysoltree', 'pysollib.pysolgtk.selectcardset', 'pysollib.pysolgtk.selectgame', 'pysollib.pysolgtk.selecttile', 'pysollib.pysolgtk.soundoptionsdialog', 'pysollib.pysolgtk.statusbar', 'pysollib.pysolgtk.timeoutsdialog', 'pysollib.pysolgtk.tkcanvas', 'pysollib.pysolgtk.tkconst', 'pysollib.pysolgtk.tkhtml', 'pysollib.pysolgtk.tkstats', 'pysollib.pysolgtk.tkutil', 'pysollib.pysolgtk.tkwidget', 'pysollib.pysolgtk.tkwrap', 'pysollib.pysolgtk.toolbar', 'pysollib.tile.card', 'pysollib.tile.colorsdialog', 'pysollib.tile.edittextdialog', 'pysollib.tile.findcarddialog', 'pysollib.tile.fontsdialog', 'pysollib.tile.gameinfodialog', 'pysollib.tile.menubar', 'pysollib.tile.playeroptionsdialog', 'pysollib.tile.progressbar', 'pysollib.tile.selectcardset', 'pysollib.tile.selectgame', 'pysollib.tile.selecttile', 'pysollib.tile.selecttree', 'pysollib.tile.solverdialog', 'pysollib.tile.soundoptionsdialog', 'pysollib.tile.statusbar', 'pysollib.tile.timeoutsdialog', 'pysollib.tile.tkcanvas', 'pysollib.tile.tkconst', 'pysollib.tile.tkhtml', 'pysollib.tile.tkstats', 'pysollib.tile.tktree', 'pysollib.tile.tkutil', 'pysollib.tile.tkwidget', 'pysollib.tile.tkwrap', 'pysollib.tile.toolbar', 'pysollib.tile.ttk', 'pysollib.tile.wizarddialog', ]:
    open(os.path.join(".", "tests", "individually-importing", "import_" + module_name + ".py"), 'w').write('''#!/usr/bin/env python
import sys
sys.path.append("./tests/lib")
from TAP.Simple import plan, ok

plan(1)
sys.path.insert(0, ".")
import %(module_name)s
ok(1, "imported")
''' % { 'module_name': module_name })
