#!/bin/bash
set -e

# Functioned-out - may be useful later.
proc_path()
{
    PATH="$(perl -lE 'my @p = split/:/,$ENV{PATH}; print join q#:#, grep { ! m#\A/opt/python# } @p;')" "$@"
}
make test
make dist
tar -xvf dist/PySolFC-*.tar.xz
(cd PySolFC-*/ && make test)
