#!/bin/bash
set -e

# Functioned-out - may be useful later.
proc_path()
{
    PATH="$(perl -lE 'my @p = split/:/,$ENV{PATH}; print join q#:#, grep { ! m#\A/opt/python# } @p;')" "$@"
}

if [ "x${TRAVIS_OS_NAME}" = "xosx" ]; then
    export TEST_TAGS=SKIP_PY2
fi
make test
make dist
tar -xvf dist/PySolFC-*.tar.xz
(cd PySolFC-*/ && make test)
