name: CI tests at GitHub

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check:

    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
        python-version:
          - 3.7
          - 3.8
          - 3.9
          - '3.10'
          - 3.11
          - 3.12
          - 3.13
        exclude:
          - os: ubuntu-24.04
            python-version: 3.7

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{matrix.python-version}}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 flake8-import-order \
          attrs configobj pycotap pysol-cards setuptools
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 . --show-source
    - name: Run unit tests
      run: |
        python -m unittest -v
    - name: Individually import each Python module
      run: |
        python scripts/gen_individual_importing_tests.py
        prove tests/individually-importing/*.py
